"use client"

import { useState } from "react"
import { Download, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"

interface ProcessedFailureMode {
  failureMode: string
  cause: string
  effect: string
  severity: number
  occurrence: number
  detection: number
  rpn: number
  recommendation?: string
}

interface DownloadPdfButtonProps {
  assetType: string
  voltageRating: string
  operatingEnvironment: string
  ageRange: string
  loadProfile: string
  assetCriticality: string
  additionalNotes: string
  failureModes: ProcessedFailureMode[]
  weibullParameters: Record<string, { shape: number; scale: number }>
}

export function DownloadPdfButton({
  assetType,
  voltageRating,
  operatingEnvironment,
  ageRange,
  loadProfile,
  assetCriticality,
  additionalNotes,
  failureModes,
  weibullParameters,
}: DownloadPdfButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false)

  const handleDownload = async () => {
    setIsGenerating(true)

    try {
      // Generate text report content
      const reportContent = generateTextReport({
        assetType,
        voltageRating,
        operatingEnvironment,
        ageRange,
        loadProfile,
        assetCriticality,
        additionalNotes,
        failureModes,
        weibullParameters,
      })

      // Create and download the file
      const blob = new Blob([reportContent], { type: "text/plain" })
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `FMEA_${assetType}_${new Date().toISOString().split("T")[0]}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (error) {
      console.error("Error generating report:", error)
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <Button onClick={handleDownload} disabled={isGenerating} variant="outline">
      {isGenerating ? (
        <>
          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          Generating...
        </>
      ) : (
        <>
          <Download className="h-4 w-4 mr-2" />
          Download Report
        </>
      )}
    </Button>
  )
}

function generateTextReport(data: DownloadPdfButtonProps): string {
  const {
    assetType,
    voltageRating,
    operatingEnvironment,
    ageRange,
    loadProfile,
    assetCriticality,
    additionalNotes,
    failureModes,
    weibullParameters,
  } = data

  let report = `FAILURE MODE AND EFFECTS ANALYSIS (FMEA) REPORT
Generated on: ${new Date().toLocaleDateString()}

ASSET INFORMATION
================
Asset Type: ${assetType}
Voltage Rating: ${voltageRating}
Operating Environment: ${operatingEnvironment}
Asset Age: ${ageRange}
Load Profile: ${loadProfile}
Asset Criticality: ${assetCriticality}
Additional Notes: ${additionalNotes || "None"}

FAILURE MODES ANALYSIS
=====================
Total Failure Modes Identified: ${failureModes.length}

`

  failureModes.forEach((mode, index) => {
    report += `${index + 1}. ${mode.failureMode}
   Cause: ${mode.cause}
   Effect: ${mode.effect}
   Severity: ${mode.severity}
   Occurrence: ${mode.occurrence}
   Detection: ${mode.detection}
   RPN: ${mode.rpn}
   Risk Level: ${mode.rpn >= 200 ? "Critical" : mode.rpn >= 100 ? "High" : mode.rpn >= 50 ? "Medium" : "Low"}

`
  })

  if (Object.keys(weibullParameters).length > 0) {
    report += `WEIBULL PARAMETERS
==================
`
    Object.entries(weibullParameters).forEach(([mode, params]) => {
      report += `${mode}:
   Shape Parameter (β): ${params.shape.toFixed(2)}
   Scale Parameter (η): ${params.scale.toFixed(2)}

`
    })
  }

  report += `SUMMARY
=======
Critical Risk Items (RPN ≥ 200): ${failureModes.filter((fm) => fm.rpn >= 200).length}
High Risk Items (RPN 100-199): ${failureModes.filter((fm) => fm.rpn >= 100 && fm.rpn < 200).length}
Medium Risk Items (RPN 50-99): ${failureModes.filter((fm) => fm.rpn >= 50 && fm.rpn < 100).length}
Low Risk Items (RPN < 50): ${failureModes.filter((fm) => fm.rpn < 50).length}

This report was generated by the ReliabilityTools.ai Platform.
`

  return report
}
